name: test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: test
        run: echo "todo"
